/*
 * Movie Streaming API
 * API for managing content (movies, series, and episodes) on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Content model module.
 * @module model/Content
 * @version 1.0.0
 */
export default class Content {
  /**
   * Constructs a new <code>Content</code>.
   * @alias module:model/Content
   * @class
   * @param type {String} 
   * @param title {String} 
   * @param releaseYear {Number} 
   * @param duration {Number} 
   * @param genre {String} 
   */
  constructor(type, title, releaseYear, duration, genre) {
    this.type = type;
    this.title = title;
    this.releaseYear = releaseYear;
    this.duration = duration;
    this.genre = genre;
  }

  /**
   * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Content} obj Optional instance to populate.
   * @return {module:model/Content} The populated <code>Content</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Content();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('synopsis'))
        obj.synopsis = ApiClient.convertToType(data['synopsis'], 'String');
      if (data.hasOwnProperty('parentSeriesId'))
        obj.parentSeriesId = ApiClient.convertToType(data['parentSeriesId'], 'Number');
      if (data.hasOwnProperty('releaseYear'))
        obj.releaseYear = ApiClient.convertToType(data['releaseYear'], 'Number');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('coverImage'))
        obj.coverImage = ApiClient.convertToType(data['coverImage'], 'String');
      if (data.hasOwnProperty('genre'))
        obj.genre = ApiClient.convertToType(data['genre'], 'String');
      if (data.hasOwnProperty('actorIds'))
        obj.actorIds = ApiClient.convertToType(data['actorIds'], ['Number']);
      if (data.hasOwnProperty('directorIds'))
        obj.directorIds = ApiClient.convertToType(data['directorIds'], ['Number']);
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Content.prototype.id = undefined;

/**
 * @member {String} type
 */
Content.prototype.type = undefined;

/**
 * @member {String} title
 */
Content.prototype.title = undefined;

/**
 * @member {String} synopsis
 */
Content.prototype.synopsis = undefined;

/**
 * @member {Number} parentSeriesId
 */
Content.prototype.parentSeriesId = undefined;

/**
 * @member {Number} releaseYear
 */
Content.prototype.releaseYear = undefined;

/**
 * @member {Number} duration
 */
Content.prototype.duration = undefined;

/**
 * @member {String} coverImage
 */
Content.prototype.coverImage = undefined;

/**
 * @member {String} genre
 */
Content.prototype.genre = undefined;

/**
 * @member {Array.<Number>} actorIds
 */
Content.prototype.actorIds = undefined;

/**
 * @member {Array.<Number>} directorIds
 */
Content.prototype.directorIds = undefined;

/**
 * @member {String} language
 */
Content.prototype.language = undefined;

/**
 * @member {String} status
 */
Content.prototype.status = undefined;

