/*
 * User and Profile Management API
 * API for managing users, profiles, and individual content lists.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UserAndProfileManagementApi);
  }
}(this, function(expect, UserAndProfileManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UserAndProfileManagementApi.ProfilesApi();
  });

  describe('(package)', function() {
    describe('ProfilesApi', function() {
      describe('usersUserIdProfilesGet', function() {
        it('should call usersUserIdProfilesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdProfilesGet call and complete the assertions
          /*

          instance.usersUserIdProfilesGet(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(UserAndProfileManagementApi.Profile);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdProfilesPost', function() {
        it('should call usersUserIdProfilesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdProfilesPost call
          /*

          instance.usersUserIdProfilesPost(body, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdProfilesProfileIdDelete', function() {
        it('should call usersUserIdProfilesProfileIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdProfilesProfileIdDelete call
          /*

          instance.usersUserIdProfilesProfileIdDelete(userId, profileId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdProfilesProfileIdGet', function() {
        it('should call usersUserIdProfilesProfileIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdProfilesProfileIdGet call and complete the assertions
          /*

          instance.usersUserIdProfilesProfileIdGet(userId, profileId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UserAndProfileManagementApi.Profile);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdProfilesProfileIdPut', function() {
        it('should call usersUserIdProfilesProfileIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdProfilesProfileIdPut call
          /*

          instance.usersUserIdProfilesProfileIdPut(body, userId, profileId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
