/*
 * User and Profile Management API
 * API for managing users, profiles, and individual content lists.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UserAndProfileManagementApi);
  }
}(this, function(expect, UserAndProfileManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UserAndProfileManagementApi.UsersApi();
  });

  describe('(package)', function() {
    describe('UsersApi', function() {
      describe('usersGet', function() {
        it('should call usersGet successfully', function(done) {
          // TODO: uncomment usersGet call and complete the assertions
          /*

          instance.usersGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(UserAndProfileManagementApi.User);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersPost', function() {
        it('should call usersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for usersPost call
          /*

          instance.usersPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdDelete', function() {
        it('should call usersUserIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdDelete call
          /*

          instance.usersUserIdDelete(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdGet', function() {
        it('should call usersUserIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdGet call and complete the assertions
          /*

          instance.usersUserIdGet(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UserAndProfileManagementApi.User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('usersUserIdPut', function() {
        it('should call usersUserIdPut successfully', function(done) {
          // TODO: uncomment, update parameter values for usersUserIdPut call
          /*

          instance.usersUserIdPut(body, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
