/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AdditionalInfoManagementApi);
  }
}(this, function(expect, AdditionalInfoManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AdditionalInfoManagementApi.ContinueWatchingApi();
  });

  describe('(package)', function() {
    describe('ContinueWatchingApi', function() {
      describe('addContinueWatching', function() {
        it('should call addContinueWatching successfully', function(done) {
          // TODO: uncomment, update parameter values for addContinueWatching call and complete the assertions
          /*

          instance.addContinueWatching(body, userId, profileId, contentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdditionalInfoManagementApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteContinueWatching', function() {
        it('should call deleteContinueWatching successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteContinueWatching call and complete the assertions
          /*

          instance.deleteContinueWatching(userId, profileId, contentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdditionalInfoManagementApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getContinueWatching', function() {
        it('should call getContinueWatching successfully', function(done) {
          // TODO: uncomment, update parameter values for getContinueWatching call and complete the assertions
          /*

          instance.getContinueWatching(userId, profileId, contentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdditionalInfoManagementApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateContinueWatching', function() {
        it('should call updateContinueWatching successfully', function(done) {
          // TODO: uncomment, update parameter values for updateContinueWatching call and complete the assertions
          /*

          instance.updateContinueWatching(body, userId, profileId, contentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AdditionalInfoManagementApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
