/*
 * User and Profile Management API
 * API for managing users, profiles, and individual content lists.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UserAndProfileManagementApi);
  }
}(this, function(expect, UserAndProfileManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Profile', function() {
      beforeEach(function() {
        instance = new UserAndProfileManagementApi.Profile();
      });

      it('should create an instance of Profile', function() {
        // TODO: update the code to test Profile
        expect(instance).to.be.a(UserAndProfileManagementApi.Profile);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "userId")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property favorites (base name: "favorites")', function() {
        // TODO: update the code to test the property favorites
        expect(instance).to.have.property('favorites');
        // expect(instance.favorites).to.be(expectedValueLiteral);
      });

      it('should have the property watchLater (base name: "watchLater")', function() {
        // TODO: update the code to test the property watchLater
        expect(instance).to.have.property('watchLater');
        // expect(instance.watchLater).to.be(expectedValueLiteral);
      });

      it('should have the property recentlyWatched (base name: "recentlyWatched")', function() {
        // TODO: update the code to test the property recentlyWatched
        expect(instance).to.have.property('recentlyWatched');
        // expect(instance.recentlyWatched).to.be(expectedValueLiteral);
      });

    });
  });

}));
