/*
 * Movie Streaming API
 * API for managing content (movies, series, and episodes) on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Actor from './model/Actor';
import Content from './model/Content';
import Director from './model/Director';
import ActorsApi from './api/ActorsApi';
import ContentsApi from './api/ContentsApi';
import DirectorsApi from './api/DirectorsApi';

/**
* API_for_managing_content__movies_series_and_episodes_on_a_streaming_platform_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MovieStreamingApi = require('index'); // See note below*.
* var xxxSvc = new MovieStreamingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MovieStreamingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MovieStreamingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MovieStreamingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Actor model constructor.
     * @property {module:model/Actor}
     */
    Actor,

    /**
     * The Content model constructor.
     * @property {module:model/Content}
     */
    Content,

    /**
     * The Director model constructor.
     * @property {module:model/Director}
     */
    Director,

    /**
    * The ActorsApi service constructor.
    * @property {module:api/ActorsApi}
    */
    ActorsApi,

    /**
    * The ContentsApi service constructor.
    * @property {module:api/ContentsApi}
    */
    ContentsApi,

    /**
    * The DirectorsApi service constructor.
    * @property {module:api/DirectorsApi}
    */
    DirectorsApi
};
