/*
 * User and Profile Management API
 * API for managing users, profiles, and individual content lists.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Profile model module.
 * @module model/Profile
 * @version 1.0.0
 */
export default class Profile {
  /**
   * Constructs a new <code>Profile</code>.
   * @alias module:model/Profile
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Profile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Profile} obj Optional instance to populate.
   * @return {module:model/Profile} The populated <code>Profile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Profile();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('favorites'))
        obj.favorites = ApiClient.convertToType(data['favorites'], ['Number']);
      if (data.hasOwnProperty('watchLater'))
        obj.watchLater = ApiClient.convertToType(data['watchLater'], ['Number']);
      if (data.hasOwnProperty('recentlyWatched'))
        obj.recentlyWatched = ApiClient.convertToType(data['recentlyWatched'], ['Number']);
    }
    return obj;
  }
}

/**
 * Unique identifier for the profile
 * @member {Number} id
 */
Profile.prototype.id = undefined;

/**
 * Name of the profile
 * @member {String} name
 */
Profile.prototype.name = undefined;

/**
 * ID of the associated user
 * @member {Number} userId
 */
Profile.prototype.userId = undefined;

/**
 * List of favorite content IDs
 * @member {Array.<Number>} favorites
 */
Profile.prototype.favorites = undefined;

/**
 * List of watch later content IDs
 * @member {Array.<Number>} watchLater
 */
Profile.prototype.watchLater = undefined;

/**
 * List of recently watched content IDs
 * @member {Array.<Number>} recentlyWatched
 */
Profile.prototype.recentlyWatched = undefined;

