/*
 * User and Profile Management API
 * API for managing users, profiles, and individual content lists.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
export default class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('contrasena'))
        obj.contrasena = ApiClient.convertToType(data['contrasena'], 'String');
      if (data.hasOwnProperty('rol'))
        obj.rol = ApiClient.convertToType(data['rol'], 'Number');
    }
    return obj;
  }
}

/**
 * Unique identifier for the user
 * @member {Number} id
 */
User.prototype.id = undefined;

/**
 * Username of the user
 * @member {String} username
 */
User.prototype.username = undefined;

/**
 * Email of the user
 * @member {String} email
 */
User.prototype.email = undefined;

/**
 * Password of the user
 * @member {String} contrasena
 */
User.prototype.contrasena = undefined;

/**
 * Role of the user (1 = Normal user, 2 = Admin)
 * @member {Number} rol
 */
User.prototype.rol = undefined;

