/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ContinuewatchingContentIdBody from '../model/ContinuewatchingContentIdBody';
import ContinuewatchingContentIdBody1 from '../model/ContinuewatchingContentIdBody1';
import InlineResponse200 from '../model/InlineResponse200';
import SuccessResponse from '../model/SuccessResponse';

/**
* ContinueWatching service.
* @module api/ContinueWatchingApi
* @version 1.0.0
*/
export default class ContinueWatchingApi {

    /**
    * Constructs a new ContinueWatchingApi. 
    * @alias module:api/ContinueWatchingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the addContinueWatching operation.
     * @callback moduleapi/ContinueWatchingApi~addContinueWatchingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add continue watching entry
     * Add a new entry for a user&#x27;s last watched minute for a specific content.
     * @param {module:model/ContinuewatchingContentIdBody1} body Data for the continue watching entry
     * @param {Number} userId The ID of the user
     * @param {Number} profileId The ID of the profile
     * @param {Number} contentId The ID of the content
     * @param {module:api/ContinueWatchingApi~addContinueWatchingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    addContinueWatching(body, userId, profileId, contentId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addContinueWatching");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling addContinueWatching");
      }
      // verify the required parameter 'profileId' is set
      if (profileId === undefined || profileId === null) {
        throw new Error("Missing the required parameter 'profileId' when calling addContinueWatching");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling addContinueWatching");
      }

      let pathParams = {
        'user_id': userId,'profile_id': profileId,'content_id': contentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SuccessResponse;

      return this.apiClient.callApi(
        '/users/{user_id}/profiles/{profile_id}/continue-watching/{content_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteContinueWatching operation.
     * @callback moduleapi/ContinueWatchingApi~deleteContinueWatchingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete continue watching entry
     * Delete a continue watching entry for a specific content by a user and profile.
     * @param {Number} userId The ID of the user
     * @param {Number} profileId The ID of the profile
     * @param {Number} contentId The ID of the content
     * @param {module:api/ContinueWatchingApi~deleteContinueWatchingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteContinueWatching(userId, profileId, contentId, callback) {
      
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteContinueWatching");
      }
      // verify the required parameter 'profileId' is set
      if (profileId === undefined || profileId === null) {
        throw new Error("Missing the required parameter 'profileId' when calling deleteContinueWatching");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling deleteContinueWatching");
      }

      let pathParams = {
        'user_id': userId,'profile_id': profileId,'content_id': contentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SuccessResponse;

      return this.apiClient.callApi(
        '/users/{user_id}/profiles/{profile_id}/continue-watching/{content_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getContinueWatching operation.
     * @callback moduleapi/ContinueWatchingApi~getContinueWatchingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get last watched minute for content
     * Retrieve the last watched minute for a specific content by a user and profile.
     * @param {Number} userId The ID of the user
     * @param {Number} profileId The ID of the profile
     * @param {Number} contentId The ID of the content
     * @param {module:api/ContinueWatchingApi~getContinueWatchingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getContinueWatching(userId, profileId, contentId, callback) {
      
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getContinueWatching");
      }
      // verify the required parameter 'profileId' is set
      if (profileId === undefined || profileId === null) {
        throw new Error("Missing the required parameter 'profileId' when calling getContinueWatching");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling getContinueWatching");
      }

      let pathParams = {
        'user_id': userId,'profile_id': profileId,'content_id': contentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/users/{user_id}/profiles/{profile_id}/continue-watching/{content_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateContinueWatching operation.
     * @callback moduleapi/ContinueWatchingApi~updateContinueWatchingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update continue watching entry
     * Update the last watched minute for a user&#x27;s content.
     * @param {module:model/ContinuewatchingContentIdBody} body Updated continue watching data
     * @param {Number} userId The ID of the user
     * @param {Number} profileId The ID of the profile
     * @param {Number} contentId The ID of the content
     * @param {module:api/ContinueWatchingApi~updateContinueWatchingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateContinueWatching(body, userId, profileId, contentId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateContinueWatching");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateContinueWatching");
      }
      // verify the required parameter 'profileId' is set
      if (profileId === undefined || profileId === null) {
        throw new Error("Missing the required parameter 'profileId' when calling updateContinueWatching");
      }
      // verify the required parameter 'contentId' is set
      if (contentId === undefined || contentId === null) {
        throw new Error("Missing the required parameter 'contentId' when calling updateContinueWatching");
      }

      let pathParams = {
        'user_id': userId,'profile_id': profileId,'content_id': contentId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SuccessResponse;

      return this.apiClient.callApi(
        '/users/{user_id}/profiles/{profile_id}/continue-watching/{content_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}