/*
 * Movie Streaming API
 * API for managing content (movies, series, and episodes) on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MovieStreamingApi);
  }
}(this, function(expect, MovieStreamingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MovieStreamingApi.ActorsApi();
  });

  describe('(package)', function() {
    describe('ActorsApi', function() {
      describe('addActor', function() {
        it('should call addActor successfully', function(done) {
          // TODO: uncomment, update parameter values for addActor call and complete the assertions
          /*

          instance.addActor(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Actor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteActor', function() {
        it('should call deleteActor successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteActor call
          /*

          instance.deleteActor(actorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getActorById', function() {
        it('should call getActorById successfully', function(done) {
          // TODO: uncomment, update parameter values for getActorById call and complete the assertions
          /*

          instance.getActorById(actorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Actor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getActors', function() {
        it('should call getActors successfully', function(done) {
          // TODO: uncomment getActors call and complete the assertions
          /*

          instance.getActors(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(MovieStreamingApi.Actor);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateActor', function() {
        it('should call updateActor successfully', function(done) {
          // TODO: uncomment, update parameter values for updateActor call and complete the assertions
          /*

          instance.updateActor(body, actorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Actor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
