/*
 * Movie Streaming API
 * API for managing content (movies, series, and episodes) on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MovieStreamingApi);
  }
}(this, function(expect, MovieStreamingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MovieStreamingApi.DirectorsApi();
  });

  describe('(package)', function() {
    describe('DirectorsApi', function() {
      describe('addDirector', function() {
        it('should call addDirector successfully', function(done) {
          // TODO: uncomment, update parameter values for addDirector call and complete the assertions
          /*

          instance.addDirector(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Director);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteDirector', function() {
        it('should call deleteDirector successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDirector call
          /*

          instance.deleteDirector(directorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDirectorById', function() {
        it('should call getDirectorById successfully', function(done) {
          // TODO: uncomment, update parameter values for getDirectorById call and complete the assertions
          /*

          instance.getDirectorById(directorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Director);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDirectors', function() {
        it('should call getDirectors successfully', function(done) {
          // TODO: uncomment getDirectors call and complete the assertions
          /*

          instance.getDirectors(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(MovieStreamingApi.Director);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateDirector', function() {
        it('should call updateDirector successfully', function(done) {
          // TODO: uncomment, update parameter values for updateDirector call and complete the assertions
          /*

          instance.updateDirector(body, directorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MovieStreamingApi.Director);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
