/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ContinuewatchingContentIdBody1 model module.
 * @module model/ContinuewatchingContentIdBody1
 * @version 1.0.0
 */
export default class ContinuewatchingContentIdBody1 {
  /**
   * Constructs a new <code>ContinuewatchingContentIdBody1</code>.
   * @alias module:model/ContinuewatchingContentIdBody1
   * @class
   * @param last_watched_minute {Number} The minute where the user stopped watching
   */
  constructor(last_watched_minute) {
    this.last_watched_minute = last_watched_minute;
  }

  /**
   * Constructs a <code>ContinuewatchingContentIdBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContinuewatchingContentIdBody1} obj Optional instance to populate.
   * @return {module:model/ContinuewatchingContentIdBody1} The populated <code>ContinuewatchingContentIdBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContinuewatchingContentIdBody1();
      if (data.hasOwnProperty('last_watched_minute'))
        obj.last_watched_minute = ApiClient.convertToType(data['last_watched_minute'], 'Number');
    }
    return obj;
  }
}

/**
 * The minute where the user stopped watching
 * @member {Number} lastWatchedMinute
 */
ContinuewatchingContentIdBody1.prototype.last_watched_minute = undefined;

