/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2002Recommendations model module.
 * @module model/InlineResponse2002Recommendations
 * @version 1.0.0
 */
export default class InlineResponse2002Recommendations {
  /**
   * Constructs a new <code>InlineResponse2002Recommendations</code>.
   * @alias module:model/InlineResponse2002Recommendations
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002Recommendations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002Recommendations} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002Recommendations} The populated <code>InlineResponse2002Recommendations</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002Recommendations();
      if (data.hasOwnProperty('contentId'))
        obj.contentId = ApiClient.convertToType(data['contentId'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }
}

/**
 * The ID of the recommended content
 * @member {Number} contentId
 */
InlineResponse2002Recommendations.prototype.contentId = undefined;

/**
 * Title of the recommended content
 * @member {String} title
 */
InlineResponse2002Recommendations.prototype.title = undefined;

