/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ReviewResponse model module.
 * @module model/ReviewResponse
 * @version 1.0.0
 */
export default class ReviewResponse {
  /**
   * Constructs a new <code>ReviewResponse</code>.
   * @alias module:model/ReviewResponse
   * @class
   * @param reviewId {Number} The ID of the review
   * @param contentId {Number} The ID of the content being reviewed
   * @param userId {Number} The ID of the user who wrote the review
   * @param profileId {Number} The ID of the profile associated with the review
   * @param rating {Number} User's rating for the content (1 to 5 stars)
   */
  constructor(reviewId, contentId, userId, profileId, rating) {
    this.reviewId = reviewId;
    this.contentId = contentId;
    this.userId = userId;
    this.profileId = profileId;
    this.rating = rating;
  }

  /**
   * Constructs a <code>ReviewResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewResponse} obj Optional instance to populate.
   * @return {module:model/ReviewResponse} The populated <code>ReviewResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewResponse();
      if (data.hasOwnProperty('review_id') || data.hasOwnProperty('reviewId'))
        obj.reviewId = ApiClient.convertToType(data['review_id'] || data['reviewId'], 'Number');
      if (data.hasOwnProperty('content_id') || data.hasOwnProperty('contentId'))
        obj.contentId = ApiClient.convertToType(data['content_id'] || data['contentId'], 'Number');
      if (data.hasOwnProperty('user_id') || data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['user_id'] || data['userId'], 'Number');
      if (data.hasOwnProperty('profile_id') || data.hasOwnProperty('profileId'))
        obj.profileId = ApiClient.convertToType(data['profile_id'] || data['profileId'], 'Number');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
    }
    return obj;
  }
}

/**
 * The ID of the review
 * @member {Number} reviewId
 */
ReviewResponse.prototype.reviewId = undefined;

/**
 * The ID of the content being reviewed
 * @member {Number} contentId
 */
ReviewResponse.prototype.contentId = undefined;

/**
 * The ID of the user who wrote the review
 * @member {Number} userId
 */
ReviewResponse.prototype.userId = undefined;

/**
 * The ID of the profile associated with the review
 * @member {Number} profileId
 */
ReviewResponse.prototype.profileId = undefined;

/**
 * User's rating for the content (1 to 5 stars)
 * @member {Number} rating
 */
ReviewResponse.prototype.rating = undefined;
