/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ReviewsResponseReviews from './ReviewsResponseReviews';

/**
 * The ReviewsResponse model module.
 * @module model/ReviewsResponse
 * @version 1.0.0
 */
export default class ReviewsResponse {
  /**
   * Constructs a new <code>ReviewsResponse</code>.
   * @alias module:model/ReviewsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReviewsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewsResponse} obj Optional instance to populate.
   * @return {module:model/ReviewsResponse} The populated <code>ReviewsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewsResponse();
      if (data.hasOwnProperty('reviews'))
        obj.reviews = ApiClient.convertToType(data['reviews'], [ReviewsResponseReviews]);
    }
    return obj;
  }
}

/**
 * Array of reviews
 * @member {Array.<module:model/ReviewsResponseReviews>} reviews
 */
ReviewsResponse.prototype.reviews = undefined;
