/*
 * Additional Info Management API
 * API for managing views, reviews, continue-watching functionality, and other additional operations for content on a streaming platform.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ViewRequest model module.
 * @module model/ViewRequest
 * @version 1.0.0
 */
export default class ViewRequest {
  /**
   * Constructs a new <code>ViewRequest</code>.
   * @alias module:model/ViewRequest
   * @class
   * @param viewCount {Number} The number of views to add
   */
  constructor(viewCount) {
    this.viewCount = viewCount;
  }

  /**
   * Constructs a <code>ViewRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViewRequest} obj Optional instance to populate.
   * @return {module:model/ViewRequest} The populated <code>ViewRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ViewRequest();
      if (data.hasOwnProperty('view_count'))
        obj.viewCount = ApiClient.convertToType(data['view_count'], 'Number');
    }
    return obj;
  }
}

/**
 * The number of views to add
 * @member {Number} viewCount
 */
ViewRequest.prototype.viewCount = undefined;

